import MeetYourAcceptedTeam from '@/components/MeetYourAcceptedTeam'
import fetchProfileByEmail from '@/database/profiles/fetchProfileByEmail'
import { useEffect } from 'react'
const Test = () => {
  const members = [
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Ale',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
    {
      profile_id: 1,
      first_name: 'Alejandroizquez',
      last_name: 'Vera',
      email: 'alexvera0109@gmail.com',
      school: 'Florida International University',
      major: 'Computer Science',
      location: 'Miami, FL',
      linkedin_link: 'https://www.linkedin.com/in/alejandrovera09/',
      github_link: 'https://github.com/AlejandroV01',
      portfolio_link: 'https://alejandrovera.com/',
      skills: [
        'JavaScript',
        'TypeScript',
        'Python',
        'HTML/CSS',
        'Java',
        'SQL (Postgres)',
        'React',
        'Node.js',
        'Flask',
        'Express.js',
        'Next.js',
        'Tailwind CSS',
        'Git',
        'AWS',
        'MongoDB',
        'Redux',
        'Storybook',
        'Styled-Components',
        'JWT',
        'Supabase',
        'REST API',
        'GitHub',
        'GitLab',
        'Postman API',
        'VS Code',
        'IntelliJ',
        'Vercel',
        'Figma',
      ],
      languages: ['English', 'Spanish'],
      created_at: '2024-03-16T21:31:19.035401+00:00',
    },
  ]

  return (
    <div>
      <h1>Test</h1>
      <MeetYourAcceptedTeam members={members} />
    </div>
  )
}

export default Test
